"""The immutable optimization artifact and its building blocks.

Every model here is `frozen=True` -- hashable and immutable by
construction, the same trade-off `app.strategy_builder` and
`app.backtesting_engine` make for their own artifacts. Arbitrary value
collections (parameter assignments, enum choices) can't be stored as raw
`dict`/`list` fields on a frozen Pydantic model, so -- following
`IndicatorReference.parameters_json`'s precedent -- they're stored as
canonical JSON strings instead.
"""

from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field

from app.backtesting_engine.models import PerformanceStatistics
from app.optimization_engine.metadata import OptimizationMetadata


class OptimizationEngineModel(BaseModel):
    """Base class for every optimization_engine model: forbids unknown fields, is immutable."""

    model_config = ConfigDict(extra="forbid", frozen=True, str_strip_whitespace=True)


class ParameterKind(str, Enum):
    INTEGER = "INTEGER"
    FLOAT = "FLOAT"
    BOOLEAN = "BOOLEAN"
    ENUM = "ENUM"
    FIXED = "FIXED"


class ParameterTarget(str, Enum):
    """What a `ParameterDefinition.name` path resolves against.

    `COMPONENT` targets an indicator/detector reference already present
    on the base `StrategyModel` (`component.<local_name>.<param_name>`);
    `CONFIGURATION` targets a `BacktestConfiguration` field
    (`configuration.<field_name>`).
    """

    COMPONENT = "COMPONENT"
    CONFIGURATION = "CONFIGURATION"


class SearchMethod(str, Enum):
    GRID = "GRID"
    RANDOM = "RANDOM"


class Objective(str, Enum):
    """What a candidate's score is derived from. Framework only -- see `app.optimization_engine.objectives`."""

    NET_PROFIT = "NET_PROFIT"
    PROFIT_FACTOR = "PROFIT_FACTOR"
    WIN_RATE = "WIN_RATE"
    EXPECTANCY = "EXPECTANCY"
    MAX_DRAWDOWN = "MAX_DRAWDOWN"
    RECOVERY_FACTOR = "RECOVERY_FACTOR"
    SHARPE_RATIO = "SHARPE_RATIO"
    CUSTOM = "CUSTOM"


class ParameterDefinition(OptimizationEngineModel):
    """One dimension of the search space.

    `name` is a dotted target path (see `ParameterTarget`). Which of
    `min_value`/`max_value`/`step`/`choices_json`/`fixed_value_json` are
    meaningful depends on `kind`:

    - `INTEGER`/`FLOAT`: `min_value`, `max_value`, and `step` (step
      defaults to 1 if omitted).
    - `BOOLEAN`: none -- always `(True, False)`.
    - `ENUM`: `choices_json` (a non-empty canonical JSON list).
    - `FIXED`: `fixed_value_json` (a single canonical JSON value) --
      included in the space but never varied, for pass-through/documentation.
    """

    name: str = Field(min_length=1, description="Dotted target path, e.g. 'component.fast_sma.window'.")
    target: ParameterTarget
    kind: ParameterKind
    min_value: float | None = None
    max_value: float | None = None
    step: float | None = None
    choices_json: str = "[]"
    fixed_value_json: str | None = None


class ParameterSpace(OptimizationEngineModel):
    """The full set of dimensions a search method explores."""

    definitions: tuple[ParameterDefinition, ...] = Field(default_factory=tuple)


class OptimizationConfiguration(OptimizationEngineModel):
    """Run-level assumptions for one optimization: what to search, and how."""

    strategy_id: str = Field(min_length=1)
    symbol: str = Field(min_length=1)
    timeframe: str = Field(min_length=1)
    search_method: SearchMethod
    objective: Objective
    max_candidates: int | None = Field(default=None, ge=1, description="Required for RANDOM search; caps GRID search if the full grid is larger.")
    random_seed: int = Field(default=42, description="Seeds RANDOM search's RNG -- same seed, same candidates.")
    top_n: int = Field(default=10, ge=1, description="How many candidates the Top Candidates report shows.")


class OptimizationCandidate(OptimizationEngineModel):
    """One parameter assignment generated by a search method, before evaluation."""

    candidate_id: str = Field(min_length=1)
    generation_index: int = Field(ge=0)
    search_method: SearchMethod
    parameters_json: str = "{}"


class OptimizationCandidateOutcome(OptimizationEngineModel):
    """The result of evaluating one `OptimizationCandidate` through the Backtesting Engine."""

    candidate_id: str = Field(min_length=1)
    parameters_json: str = "{}"
    succeeded: bool
    strategy_model_id: str | None = None
    strategy_checksum: str | None = None
    backtest_checksum: str | None = None
    statistics: PerformanceStatistics | None = None
    score: float | None = None
    rank: int | None = None
    error_message: str | None = None


class OptimizationHistory(OptimizationEngineModel):
    """Every candidate's outcome, in generation order."""

    entries: tuple[OptimizationCandidateOutcome, ...] = Field(default_factory=tuple)


class OptimizationStatistics(OptimizationEngineModel):
    """Aggregate statistics across the whole optimization run."""

    total_candidates: int = Field(ge=0, default=0)
    evaluated_candidates: int = Field(ge=0, default=0)
    failed_candidates: int = Field(ge=0, default=0)
    objective: Objective
    best_score: float | None = None
    worst_score: float | None = None
    mean_score: float | None = None
    best_candidate_id: str | None = None


class OptimizationResult(OptimizationEngineModel):
    """The complete, immutable outcome of one optimization run.

    Immutable, serializable, versioned, and hashable -- the single
    artifact downstream engines (Walk Forward & Monte Carlo) will
    consume instead of re-running the search themselves.
    """

    result_id: str = Field(min_length=1)
    metadata: OptimizationMetadata
    configuration: OptimizationConfiguration
    parameter_space: ParameterSpace
    candidates: tuple[OptimizationCandidate, ...] = Field(default_factory=tuple)
    history: OptimizationHistory
    statistics: OptimizationStatistics
    best_candidate_id: str | None = None
    checksum: str = Field(min_length=1)
    built_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
