"""SDL Generator: assembles extracted mentions into a DRAFT SDL document.

Builds a real `app.sdl.models.StrategyDefinition` -- the platform's
single source of truth for strategies -- reusing its existing
constructors directly (never a new/parallel schema). Rule conditions are
carried through as the extracted descriptive text verbatim, never parsed
or converted into executable expressions here (that stays a human,
manual step, exactly like every other documentation-style SDL example in
this codebase). This is presentation/assembly only: it never validates,
never registers, never executes anything.
"""

import re

from app.ai_extraction.analyzer import StrategyOverview
from app.ai_extraction.models import DetectorMention, IndicatorMention, RiskMention, RuleMention, SessionMention, TimeframeMention
from app.sdl.models import IndicatorSpec, Market, Metadata, RiskManagement, Rule, StopLossRule, StrategyDefinition, TakeProfitRule, TradeManagement

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(text: str) -> str:
    slug = _SLUG_RE.sub("-", text.strip().lower()).strip("-")
    return slug or "untitled"


class SDLGenerator:
    """Builds a draft `StrategyDefinition` from already-extracted mentions."""

    def generate(
        self,
        overview: StrategyOverview,
        indicators: tuple[IndicatorMention, ...],
        detectors: tuple[DetectorMention, ...],
        entry_rules: tuple[RuleMention, ...],
        exit_rules: tuple[RuleMention, ...],
        risk_mentions: tuple[RiskMention, ...],
        sessions: tuple[SessionMention, ...],
        timeframes: tuple[TimeframeMention, ...],
    ) -> StrategyDefinition:
        metadata = Metadata(
            id=_slugify(overview.name),
            name=overview.name,
            description=overview.description or None,
            strategy_version="0.1.0-draft",
            category="extracted-draft",
        )

        component_specs = []
        seen_types: set[str] = set()
        for mention in (*indicators, *detectors):
            if mention.matched_type in seen_types:
                continue
            seen_types.add(mention.matched_type)
            component_specs.append(IndicatorSpec(name=f"{_slugify(mention.matched_type).replace('-', '_')}_{len(component_specs)}", type=mention.matched_type, params={}))

        entry_rule_specs = [Rule(name=f"entry_rule_{i + 1}", condition=mention.raw_text) for i, mention in enumerate(entry_rules)]
        exit_rule_specs = [Rule(name=f"exit_rule_{i + 1}", condition=mention.raw_text) for i, mention in enumerate(exit_rules)]

        timeframe_codes = sorted({mention.timeframe for mention in timeframes}) or ["UNKNOWN"]
        session_names = sorted({mention.session_name for mention in sessions})

        return StrategyDefinition(
            metadata=metadata,
            market=Market(asset_class="unknown"),
            symbols=["UNKNOWN"],
            timeframes=timeframe_codes,
            primary_timeframe=timeframe_codes[0],
            sessions=session_names,
            indicators=component_specs,
            entry_rules=entry_rule_specs,
            exit_rules=exit_rule_specs,
            risk_management=self._build_risk_management(risk_mentions),
            trade_management=self._build_trade_management(risk_mentions),
            tags=["extracted", "draft"],
            notes="Draft generated by the AI Strategy Extraction Engine. Requires human review and approval before use (see PROJECT_VISION.md's YouTube strategy workflow).",
        )

    @staticmethod
    def _build_risk_management(risk_mentions: tuple[RiskMention, ...]) -> RiskManagement | None:
        position_sizing = next((m for m in risk_mentions if m.category == "position_sizing" and m.value is not None), None)
        max_drawdown = next((m for m in risk_mentions if m.category == "max_drawdown" and m.value is not None), None)
        if position_sizing is None and max_drawdown is None and not risk_mentions:
            return None
        return RiskManagement(
            max_risk_per_trade_pct=position_sizing.value if position_sizing else None,
            max_daily_loss_pct=max_drawdown.value if max_drawdown else None,
            notes="; ".join(m.raw_text for m in risk_mentions) or None,
        )

    @staticmethod
    def _build_trade_management(risk_mentions: tuple[RiskMention, ...]) -> TradeManagement | None:
        stop_loss_mention = next((m for m in risk_mentions if m.category == "stop_loss"), None)
        take_profit_mention = next((m for m in risk_mentions if m.category == "take_profit"), None)
        risk_reward_mention = next((m for m in risk_mentions if m.category == "risk_reward"), None)
        if stop_loss_mention is None and take_profit_mention is None and risk_reward_mention is None:
            return None

        stop_loss = StopLossRule(type="detected", value=stop_loss_mention.value, notes=stop_loss_mention.raw_text) if stop_loss_mention else None
        take_profit = None
        if take_profit_mention or risk_reward_mention:
            take_profit = TakeProfitRule(
                type="detected",
                value=take_profit_mention.value if take_profit_mention else None,
                risk_reward_ratio=risk_reward_mention.value if risk_reward_mention else None,
                notes=(take_profit_mention or risk_reward_mention).raw_text,
            )
        return TradeManagement(stop_loss=stop_loss, take_profit=take_profit)
