"""Pure, deterministic MQL5 text templates.

Every `render_*` function is a pure string transform: given the same
arguments it always returns the same text, byte for byte. No template
here ever reads the clock, randomness, or any live system state --
determinism is what lets `app.ea_generator.compiler` guarantee "same
input = identical EA source = identical checksum".
"""

from app.ea_generator.models import (
    EAGeneratorConfiguration,
    GeneratedIndicatorDeclaration,
    GeneratedInput,
    GeneratedRiskParameters,
    GeneratedRuleBlock,
    GeneratedTradeManagement,
)
from app.strategy_builder.models import StrategyModel

_RULE_HEADING = {
    "filters": "Filters",
    "entry_rules": "Entry Rules",
    "exit_rules": "Exit Rules",
}


def render_header(strategy_model: StrategyModel, configuration: EAGeneratorConfiguration) -> str:
    ea_name = configuration.ea_name or strategy_model.metadata.name
    lines = [
        "//+------------------------------------------------------------------+",
        f"//| {ea_name}",
        "//| Generated by QuantForge AI EA Generator",
        "//| Offline, deterministic source-code generator -- NOT a live EA.",
        "//| Review and complete every TODO before compiling in MetaEditor.",
        f"//| Strategy id:       {strategy_model.metadata.id}",
        f"//| Strategy checksum: {strategy_model.checksum}",
        f"//| Author:            {configuration.author}",
        "//+------------------------------------------------------------------+",
        '#property copyright "QuantForge AI"',
        '#property link      ""',
        '#property version   "1.00"',
        "#property strict",
        "",
    ]
    return "\n".join(lines)


def render_inputs(inputs: tuple[GeneratedInput, ...], include_comments: bool) -> str:
    lines = ["// ---- Input parameters ----------------------------------------------"]
    for item in inputs:
        comment = f"  // {item.comment}" if include_comments and item.comment else ""
        lines.append(f"input {item.mql_type} {item.name} = {item.default_value};{comment}")
    lines.append("")
    return "\n".join(lines)


def render_indicator_declarations(declarations: tuple[GeneratedIndicatorDeclaration, ...], include_comments: bool) -> str:
    lines = ["// ---- Indicator / Smart Money Concept declarations --------------------"]
    if not declarations:
        lines.append("// (none declared by this strategy)")
    for item in declarations:
        params = ", ".join(item.parameters) if item.parameters else "-"
        timeframe = item.timeframe or "chart period"
        if include_comments:
            lines.append(f"// [{item.component_kind}] {item.local_name} = {item.type}({params}) on {timeframe}")
        lines.append(f"// TODO: declare and initialize handle for '{item.local_name}' ({item.type}) in OnInit().")
    lines.append("")
    return "\n".join(lines)


def render_risk_parameters(risk: GeneratedRiskParameters, include_comments: bool) -> str:
    lines = ["// ---- Risk management --------------------------------------------------"]
    if include_comments:
        lines.append(f"// Magic number: {risk.magic_number} | Lot size: {risk.lot_size} | SL: {risk.stop_loss_points}pt | TP: {risk.take_profit_points}pt | Max positions: {risk.max_open_positions}")
    lines.append("")
    return "\n".join(lines)


def _render_rule_block(block: GeneratedRuleBlock, include_comments: bool) -> list[str]:
    lines = []
    if include_comments:
        lines.append(f"// Rule '{block.local_name}': {block.condition}")
    function_name = f"Check_{block.section}_{block.local_name}".replace("-", "_").replace(" ", "_")
    lines.append(f"bool {function_name}()")
    lines.append("{")
    lines.append(f"   // TODO: translate condition into MQL5: {block.condition}")
    lines.append("   return false;")
    lines.append("}")
    lines.append("")
    return lines


def render_trade_management(trade_management: GeneratedTradeManagement, include_comments: bool) -> str:
    lines = ["// ---- Trade management skeleton -----------------------------------------"]
    for section, blocks in (
        ("filters", trade_management.filters),
        ("entry_rules", trade_management.entry_rules),
        ("exit_rules", trade_management.exit_rules),
    ):
        lines.append(f"// {_RULE_HEADING[section]}")
        if not blocks:
            lines.append(f"// (no {_RULE_HEADING[section].lower()} defined by this strategy)")
        for block in blocks:
            lines.extend(_render_rule_block(block, include_comments))
    return "\n".join(lines)


def render_lifecycle_skeleton() -> str:
    return "\n".join(
        [
            "// ---- Standard MQL5 lifecycle skeleton ----------------------------------",
            "int OnInit()",
            "{",
            "   // TODO: initialize indicator handles declared above.",
            "   return(INIT_SUCCEEDED);",
            "}",
            "",
            "void OnDeinit(const int reason)",
            "{",
            "   // TODO: release indicator handles declared above.",
            "}",
            "",
            "void OnTick()",
            "{",
            "   // TODO: evaluate filters, then entry/exit rules, then place/manage orders",
            "   // using InpLotSize / InpStopLossPoints / InpTakeProfitPoints / InpMagicNumber.",
            "}",
            "",
        ]
    )


def assemble(
    strategy_model: StrategyModel,
    configuration: EAGeneratorConfiguration,
    inputs: tuple[GeneratedInput, ...],
    indicator_declarations: tuple[GeneratedIndicatorDeclaration, ...],
    risk_parameters: GeneratedRiskParameters,
    trade_management: GeneratedTradeManagement,
) -> str:
    """Assemble every rendered section into the final, complete `.mq5` source text."""
    sections = [
        render_header(strategy_model, configuration),
        render_inputs(inputs, configuration.include_comments),
        render_indicator_declarations(indicator_declarations, configuration.include_comments),
        render_risk_parameters(risk_parameters, configuration.include_comments),
        render_trade_management(trade_management, configuration.include_comments),
        render_lifecycle_skeleton(),
    ]
    return "\n".join(sections).rstrip("\n") + "\n"
